"""
SquirrelDB Python SDK
Generated by sdk-generator v0.1.0
DO NOT EDIT MANUALLY
"""

from .types import Document, ChangeEvent, Bucket, StorageObject
from .client import SquirrelDB
from .cache import Cache
from .storage import Storage
from .query import (
    QueryBuilder,
    FieldExpr,
    FilterCondition,
    SortSpec,
    StructuredQuery,
    ChangesOptions,
    table,
    field_expr,
    and_,
    or_,
    not_,
)

__version__ = "0.1.0"
__all__ = [
    "Document",
    "ChangeEvent",
    "Bucket",
    "StorageObject",
    "SquirrelDB",
    "Cache",
    "Storage",
    "QueryBuilder",
    "FieldExpr",
    "FilterCondition",
    "SortSpec",
    "StructuredQuery",
    "ChangesOptions",
    "table",
    "field_expr",
    "and_",
    "or_",
    "not_",
]
